# Generated by Django 5.0.1 on 2024-02-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwd_manager',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
