# Generated by Django 5.0.1 on 2024-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwd_app', '0002_alter_passwd_manager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwd_manager',
            name='passwd',
            field=models.CharField(max_length=20),
        ),
    ]
